services:
  - type: web
    name: interview-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DLIB_USE_CUDA
        value: false
    autoDeploy: true
    branch: main
    region: oregon

  - type: web
    name: interview-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --port $PORT
    staticPublishPath: frontend/dist
