services:
  - type: web
    name: navin-career-advisor
    env: python
    plan: free    # or standard depending on your needs
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
      npm install
      npm run build
    startCommand: |
      uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.13
    nodeVersion: 22.16.0
