services:
  - type: web
    name: interview-backend
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
